version: '3.6'
services: 
  postgres:
    image: postgres:latest
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "5m"
    env_file:
      - .env
    ports: 
      - "5432:5432"
    volumes: 
      - ./:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      ecs-local-network: null
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "5m"
    env_file:
      - .env
    ports: 
        - "16543:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin4/storage/bkp
    depends_on: 
        - postgres
    networks:
      ecs-local-network: null
  metabase:
    image: metabase/metabase
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "5m"
    env_file:
      - .env
    ports: 
        - "3000:3000"
    volumes:
      - ./metabase_data:/metabase-data
    depends_on: 
        - postgres
    networks:
      ecs-local-network: null
volumes:
  postgres_data:
networks:
  ecs-local-network:
    external: true
